export const KTDS_TOKENS = {
  color: {
    primary: '#1a75ff',
    primaryText: '#186ae8',
    primaryActive: '#1360d6',
    primaryFillNeutral: '#F2F5F9',
    surface: '#ffffff',
    surfaceAlt: '#f7f7f8',
    text: '#171719',
    textNeutral: '#474a4f',
    textAlternative: '#9a9ba0',
    border: '#c5c6c9',
    borderAlt: '#dcdde0',
    fillNeutral: '#dfe0e2',
    fillAlt: '#e9eaeb',
    positive: '#00c244',
    caution: '#ff9200',
    negative: '#ff4242',
    info: '#0066ff',
    onPrimary: '#ffffff',
    dimmer: 'rgba(23,23,25,0.48)',
  },
  typography: {
    fontFamily: "'Pretendard', -apple-system, BlinkMacSystemFont, sans-serif",
    displayLg: { size: 32, weight: 700, lineHeight: 1.25 },
    headlineLg: { size: 24, weight: 700, lineHeight: 1.33 },
    titleLg: { size: 20, weight: 600, lineHeight: 1.4 },
    titleMd: { size: 18, weight: 600, lineHeight: 1.44 },
    bodyLg: { size: 16, weight: 400, lineHeight: 1.5 },
    bodyMd: { size: 14, weight: 400, lineHeight: 1.5 },
    labelLg: { size: 14, weight: 600, lineHeight: 1.5 },
    captionLg: { size: 12, weight: 400, lineHeight: 1.4 },
    captionSm: { size: 11, weight: 400, lineHeight: 1.36 },
  },
  radius: {
    none: 0,
    xs: 2,
    sm: 4,
    base: 6,
    md: 8,
    lg: 12,
    xl: 16,
    xxl: 20,
    full: 9999,
  },
  spacing: {
    xxs: 4,
    xs: 8,
    sm: 12,
    base: 16,
    md: 20,
    lg: 24,
    xl: 32,
    xxl: 40,
    xxxl: 48,
    section: 64,
  },
  layout: {
    pagePadding: 16,
    pagePaddingWeb: 24,
    sectionGap: 24,
    cardPadding: 20,
    cardGap: 16,
    itemGap: 8,
    headerHeight: 56,
    tabbarHeight: 72,
    navSideWidth: 240,
  },
  shadow: {
    card: '0 5px 10px rgba(0,0,0,0.05)',
    overlay: '0 -8px 32px rgba(23,23,25,0.14)',
  },
} as const;

// Compatibility aliases for the original Playground components.
export const KTDS_LEGACY_TOKENS = {
  primary: KTDS_TOKENS.color.primary,
  primaryDark: KTDS_TOKENS.color.primaryActive,
  bg: KTDS_TOKENS.color.primaryFillNeutral,
  surface: KTDS_TOKENS.color.surface,
  text: KTDS_TOKENS.color.text,
  textNeutral: KTDS_TOKENS.color.textNeutral,
  textAlt: KTDS_TOKENS.color.textAlternative,
  border: KTDS_TOKENS.color.border,
  borderAlt: KTDS_TOKENS.color.borderAlt,
  negative: KTDS_TOKENS.color.negative,
  positive: KTDS_TOKENS.color.positive,
  fontFamily: KTDS_TOKENS.typography.fontFamily,
} as const;
