import Link from 'next/link'
import {
  AlertCircle, ArrowLeft, Bell, Check, ChevronDown, ChevronRight, Clock3,
  Download, Info, LoaderCircle, Menu, MoreHorizontal, Plus, Search, Settings,
  Sparkles, Upload, User, X,
} from 'lucide-react'
import { AUI_TOKEN_GROUPS, AUI_TOKEN_ENTRIES, AUI_SCHEMA_VERSION } from '@/lib/aide-product-tokens'

/* Every list below is derived from aide-product-ui.md — never hand-listed here.
   Editing the md contract updates this showcase and the product together. */

const colors = (AUI_TOKEN_GROUPS.color ?? []).map((t) => [t.key, `var(${t.cssVar})`] as const)

const radii = (AUI_TOKEN_GROUPS.radius ?? [])
  .filter((t) => t.key !== 'pill')
  .map((t) => [t.key, `var(${t.cssVar})`] as const)

const spacing = (AUI_TOKEN_GROUPS.space ?? []).map(
  (t) => [t.key.replace('space-', ''), parseInt(t.value, 10)] as const,
)

const motion = (AUI_TOKEN_GROUPS.motion ?? []).filter((t) => t.key !== 'easing')

/** Rebuild each typography scale from its `--aui-type-<scale>-*` parts. */
const typeScale = Object.values(
  (AUI_TOKEN_GROUPS.typography ?? []).reduce<
    Record<string, { name: string; size: string; leading: string; weight: string; role: string }>
  >((acc, entry) => {
    const match = entry.cssVar.match(/^--aui-type-(.+)-(size|leading|weight|tracking|family)$/)
    if (!match) return acc
    const [, scale, part] = match
    const row = (acc[scale] ??= {
      name: scale.replace(/-/g, ' '),
      size: '',
      leading: '',
      weight: '',
      role: entry.description ?? '',
    })
    if (part === 'size') row.size = entry.value
    if (part === 'leading') row.leading = entry.value
    if (part === 'weight') row.weight = entry.value
    return acc
  }, {}),
).filter((row) => row.size && row.leading)

function Section({ id, eyebrow, title, description, children }: { id: string; eyebrow: string; title: string; description: string; children: React.ReactNode }) {
  return <section className="aui-section" id={id}><div className="aui-section-head"><span>{eyebrow}</span><h2>{title}</h2><p>{description}</p></div>{children}</section>
}

function DemoButton({ variant = 'primary', children, disabled = false }: { variant?: string; children: React.ReactNode; disabled?: boolean }) {
  return <button className={`ds-button ${variant}`} disabled={disabled}>{children}</button>
}

function Field({ label, placeholder, state }: { label: string; placeholder: string; state?: 'error' | 'success' | 'disabled' }) {
  return <label className={`ds-field ${state ?? ''}`}><span>{label}</span><div><input placeholder={placeholder} disabled={state === 'disabled'} />{state === 'success' && <Check size={16} />}{state === 'error' && <AlertCircle size={16} />}</div>{state === 'error' && <small>입력 내용을 다시 확인해 주세요.</small>}</label>
}

export default function AideProductUIShowcase() {
  return <main className="product-showcase">
    <style>{`
      .product-showcase{min-height:100vh;background:var(--aui-page);color:var(--aui-text);font-family:var(--font-pretendard);scroll-behavior:smooth}.product-showcase *{box-sizing:border-box}.product-showcase button,.product-showcase input{font:inherit}
      .showcase-nav{position:sticky;top:0;z-index:50;height:64px;padding:0 max(24px,calc((100vw - 1200px)/2));display:flex;align-items:center;justify-content:space-between;background:color-mix(in srgb,var(--aui-surface) 92%,transparent);backdrop-filter:blur(24px);border-bottom:1px solid var(--aui-border-subtle)}.showcase-nav a{display:flex;align-items:center;gap:8px;color:var(--aui-text);text-decoration:none;font-size:14px;font-weight:600}.showcase-nav div{display:flex;align-items:center;gap:8px}.doc-badge{padding:6px 10px;border-radius:var(--aui-radius-pill);background:var(--aui-primary-soft);color:var(--aui-primary-heavy);font-size:12px;font-weight:700}.version{font-size:12px;color:var(--aui-text-muted)}
      .showcase-hero{max-width:1200px;margin:auto;padding:72px 24px 52px;display:grid;grid-template-columns:1.2fr .8fr;gap:48px;align-items:end}.showcase-hero h1{font-size:48px;line-height:1.12;letter-spacing:-1.4px;margin:16px 0}.showcase-hero p{max-width:680px;color:var(--aui-text-muted);font-size:16px;line-height:1.7}.hero-kicker{color:var(--aui-primary);font-size:12px;font-weight:700;letter-spacing:.08em}.principle-list{display:grid;gap:8px}.principle-list div{display:flex;gap:12px;align-items:center;padding:12px 14px;background:var(--aui-surface);border:1px solid var(--aui-border-subtle);border-radius:var(--aui-radius-control);font-size:13px}.principle-list b{color:var(--aui-primary)}
      .jump-nav{max-width:1200px;margin:0 auto 20px;padding:0 24px;display:flex;gap:8px;flex-wrap:wrap}.jump-nav a{padding:8px 12px;border-radius:var(--aui-radius-pill);border:1px solid var(--aui-border);background:var(--aui-surface);color:var(--aui-text-neutral);font-size:12px;text-decoration:none}.jump-nav a:hover{border-color:var(--aui-primary);color:var(--aui-primary)}
      .aui-section{max-width:1200px;margin:auto;padding:52px 24px;border-top:1px solid var(--aui-border-subtle)}.aui-section-head{max-width:720px;margin-bottom:28px}.aui-section-head>span{color:var(--aui-primary);font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.aui-section-head h2{font-size:28px;line-height:38px;margin:6px 0}.aui-section-head p{color:var(--aui-text-muted);font-size:15px;line-height:24px}
      .color-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:12px}.swatch{overflow:hidden;background:var(--aui-surface);border:1px solid var(--aui-border-subtle);border-radius:var(--aui-radius-control)}.swatch-color{height:68px}.swatch-label{padding:10px}.swatch-label b,.swatch-label code{display:block}.swatch-label b{font-size:12px}.swatch-label code{margin-top:3px;font-size:10px;color:var(--aui-text-muted)}
      .type-board,.demo-card{background:var(--aui-surface);border:1px solid var(--aui-border-subtle);border-radius:var(--aui-radius-card)}.type-board{padding:8px 20px}.type-row{display:grid;grid-template-columns:110px 1fr 180px;gap:16px;align-items:center;padding:18px 0;border-bottom:1px solid var(--aui-border-subtle)}.type-row:last-child{border:0}.type-row>span,.type-row>code{font-size:12px;color:var(--aui-text-muted)}
      .foundation-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.demo-card{padding:20px}.demo-card h3{font-size:15px;margin:0 0 16px}.token-row{display:flex;align-items:center;gap:10px;min-height:34px;font-size:12px;color:var(--aui-text-muted)}.space-bar{height:8px;border-radius:2px;background:var(--aui-primary)}.radius-box{width:42px;height:28px;background:var(--aui-primary-soft);border:1px solid var(--aui-primary)}.shadow-box{height:52px;display:grid;place-items:center;margin:12px 0;background:var(--aui-surface);border-radius:var(--aui-radius-control);font-size:11px;color:var(--aui-text-muted)}.shadow-box.card{box-shadow:var(--aui-shadow-card)}.shadow-box.elevated{box-shadow:var(--aui-shadow-elevated)}
      .component-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.component-wide{grid-column:1/-1}.component-title{display:flex;align-items:center;justify-content:space-between;margin-bottom:18px}.component-title h3{margin:0}.component-title span{font-size:11px;color:var(--aui-text-muted)}.row{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.stack{display:grid;gap:12px}
      .ds-button{height:40px;padding:0 15px;border:0;border-radius:var(--aui-radius-control);display:inline-flex;align-items:center;justify-content:center;gap:7px;font-size:14px;font-weight:600;cursor:pointer;transition:all var(--aui-motion-fast) var(--aui-motion-easing)}.ds-button.primary{background:var(--aui-primary);color:var(--aui-on-primary)}.ds-button.primary:hover{background:var(--aui-primary-strong)}.ds-button.secondary{background:var(--aui-fill);color:var(--aui-text)}.ds-button.outline{background:var(--aui-surface);color:var(--aui-text);box-shadow:inset 0 0 0 1px var(--aui-border)}.ds-button.ghost{background:transparent;color:var(--aui-text-neutral)}.ds-button.destructive{background:var(--aui-negative);color:var(--aui-on-primary)}.ds-button.compact{height:32px;font-size:13px}.ds-button.prominent{height:48px}.ds-button:disabled{background:var(--aui-fill);color:var(--aui-text-disabled);cursor:not-allowed}.icon-button{width:40px;height:40px;padding:0;border:1px solid var(--aui-border);border-radius:var(--aui-radius-control);background:var(--aui-surface);color:var(--aui-text-neutral);display:grid;place-items:center}.icon-button.compact{width:32px;height:32px}
      .ds-field{display:grid;gap:6px}.ds-field>span{font-size:13px;font-weight:600}.ds-field>div{height:40px;display:flex;align-items:center;padding:0 12px;border:1px solid var(--aui-border);border-radius:var(--aui-radius-control);background:var(--aui-surface)}.ds-field input{width:100%;border:0;outline:0;background:transparent;color:var(--aui-text);font-size:14px}.ds-field input::placeholder{color:var(--aui-text-assistive)}.ds-field>div:focus-within{border-color:var(--aui-primary);box-shadow:0 0 0 2px var(--aui-primary-tint)}.ds-field.error>div{border-color:var(--aui-negative)}.ds-field.error svg,.ds-field.error small{color:var(--aui-negative)}.ds-field.success svg{color:var(--aui-positive)}.ds-field.disabled>div{background:var(--aui-surface-muted)}.ds-field small{font-size:12px}.form-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}
      .choice{height:40px;display:inline-flex;align-items:center;gap:8px;font-size:14px}.check-box,.radio-dot{width:18px;height:18px;display:grid;place-items:center;border:1px solid var(--aui-border);background:var(--aui-surface)}.check-box{border-radius:5px}.check-box.active{color:var(--aui-on-primary);background:var(--aui-primary);border-color:var(--aui-primary)}.radio-dot{border-radius:50%}.radio-dot.active:after{content:'';width:10px;height:10px;border-radius:50%;background:var(--aui-primary)}.switch{width:40px;height:24px;padding:3px;border-radius:var(--aui-radius-pill);background:var(--aui-fill-strong)}.switch:after{content:'';display:block;width:18px;height:18px;border-radius:50%;background:var(--aui-surface);box-shadow:var(--aui-shadow-soft)}.switch.active{background:var(--aui-primary)}.switch.active:after{margin-left:16px}.chip,.badge{display:inline-flex;align-items:center;gap:5px;border-radius:var(--aui-radius-pill);font-size:12px}.chip{height:32px;padding:0 11px;background:var(--aui-fill);color:var(--aui-text-neutral)}.chip.active{background:var(--aui-primary-soft);color:var(--aui-primary-heavy);font-weight:600}.badge{padding:4px 8px;background:var(--aui-surface-muted)}.badge.success{background:var(--aui-positive);color:var(--aui-on-primary)}.badge.warning{background:var(--aui-caution-soft);color:var(--aui-caution-text)}
      .segmented{display:grid;grid-template-columns:repeat(3,1fr);padding:4px;border-radius:var(--aui-radius-control);background:var(--aui-fill)}.segmented button{height:32px;border:0;border-radius:9px;background:transparent;color:var(--aui-text-muted);font-size:13px}.segmented button.active{background:var(--aui-surface);color:var(--aui-primary);font-weight:600;box-shadow:var(--aui-shadow-soft)}.tabs{display:flex;gap:22px;border-bottom:1px solid var(--aui-border-subtle)}.tabs button{height:42px;border:0;border-bottom:2px solid transparent;background:transparent;color:var(--aui-text-muted);font-size:14px}.tabs button.active{color:var(--aui-primary);border-color:var(--aui-primary);font-weight:600}
      .list-cell{min-height:56px;display:flex;align-items:center;gap:12px;border-bottom:1px solid var(--aui-border-subtle)}.list-cell:last-child{border:0}.avatar{width:36px;height:36px;display:grid;place-items:center;border-radius:50%;background:var(--aui-primary-soft);color:var(--aui-primary)}.list-copy{flex:1;display:grid;gap:2px}.list-copy b{font-size:14px}.list-copy span{font-size:12px;color:var(--aui-text-muted)}.metric-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.metric{padding:16px;border-radius:var(--aui-radius-control);background:var(--aui-surface-muted)}.metric span{font-size:12px;color:var(--aui-text-muted)}.metric strong{display:block;margin-top:6px;font-size:22px}.progress{height:7px;margin-top:12px;border-radius:var(--aui-radius-pill);background:var(--aui-fill)}.progress i{display:block;width:68%;height:100%;border-radius:inherit;background:var(--aui-primary)}
      .feedback-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.feedback{display:flex;align-items:flex-start;gap:10px;padding:14px;border-radius:var(--aui-radius-control);font-size:13px;line-height:19px}.feedback.info{background:var(--aui-primary-soft);color:var(--aui-primary-heavy)}.feedback.success{background:color-mix(in srgb,var(--aui-positive) 10%,var(--aui-surface));color:var(--aui-text)}.feedback.warning{background:var(--aui-caution-soft);color:var(--aui-caution-text)}.feedback.error{background:var(--aui-negative-soft);color:var(--aui-negative)}.toast{display:flex;align-items:center;gap:10px;padding:12px 14px;border-radius:var(--aui-radius-control);background:var(--aui-inverse-surface);color:var(--aui-on-dark);box-shadow:var(--aui-shadow-elevated);font-size:13px}.toast span{flex:1}.skeleton{height:12px;border-radius:6px;background:var(--aui-fill);position:relative;overflow:hidden}.skeleton.wide{width:82%}.skeleton.mid{width:56%}.empty{display:grid;justify-items:center;text-align:center;padding:28px}.empty-icon{width:48px;height:48px;display:grid;place-items:center;border-radius:50%;background:var(--aui-primary-soft);color:var(--aui-primary)}.empty h4{margin:12px 0 4px}.empty p{margin:0 0 16px;font-size:13px;color:var(--aui-text-muted)}
      .overlay-stage{min-height:350px;padding:28px;display:grid;place-items:center;border-radius:var(--aui-radius-card);background:var(--aui-scrim-soft)}.dialog{width:min(100%,460px);padding:22px;background:var(--aui-surface);border-radius:var(--aui-radius-overlay);box-shadow:var(--aui-shadow-elevated)}.dialog-head{display:flex;align-items:center;justify-content:space-between}.dialog h3{margin:0;font-size:18px}.dialog p{margin:12px 0 22px;color:var(--aui-text-muted);font-size:14px;line-height:21px}.dialog-actions{display:flex;justify-content:flex-end;gap:8px}.popover{width:230px;margin-left:auto;padding:8px;border:1px solid var(--aui-border-subtle);border-radius:var(--aui-radius-control);background:var(--aui-surface);box-shadow:var(--aui-shadow-elevated)}.popover div{height:38px;display:flex;align-items:center;gap:9px;padding:0 10px;border-radius:8px;font-size:13px}.popover div:hover{background:var(--aui-fill)}
      .layout-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.layout-preview{height:220px;overflow:hidden;border:1px solid var(--aui-border);border-radius:var(--aui-radius-card);background:var(--aui-page)}.layout-preview header{height:36px;background:var(--aui-surface);border-bottom:1px solid var(--aui-border-subtle)}.layout-preview .body{height:184px;display:flex}.layout-preview aside{width:30%;background:var(--aui-surface);border-right:1px solid var(--aui-border-subtle)}.layout-preview article{flex:1;padding:12px}.layout-preview article i{display:block;height:18px;margin-bottom:8px;border-radius:6px;background:var(--aui-fill)}.layout-preview article i:first-child{width:55%;background:var(--aui-primary-soft)}.layout-name{margin-top:10px;display:grid;gap:2px}.layout-name b{font-size:14px}.layout-name span{font-size:12px;color:var(--aui-text-muted)}
      .a11y-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.a11y-item{padding:14px;border:1px solid var(--aui-border-subtle);border-radius:var(--aui-radius-control);background:var(--aui-surface);font-size:13px}.a11y-item:before{content:'✓';color:var(--aui-positive);font-weight:800;margin-right:8px}
      @media(max-width:900px){.showcase-hero{grid-template-columns:1fr}.color-grid{grid-template-columns:repeat(3,1fr)}.foundation-grid,.layout-grid{grid-template-columns:repeat(2,1fr)}}
      @media(max-width:620px){.showcase-nav .version{display:none}.showcase-hero{padding-top:48px}.showcase-hero h1{font-size:36px}.color-grid,.component-grid,.foundation-grid,.layout-grid,.feedback-grid,.form-grid,.metric-grid,.a11y-grid{grid-template-columns:1fr}.component-wide{grid-column:auto}.type-row{grid-template-columns:82px 1fr}.type-row code{display:none}.dialog-actions{flex-direction:column-reverse}.dialog-actions .ds-button{width:100%}}
      @media(prefers-reduced-motion:reduce){.product-showcase *{scroll-behavior:auto!important;transition-duration:.01ms!important;animation-duration:.01ms!important}}
    `}</style>

    <nav className="showcase-nav"><Link href="/"><ArrowLeft size={18}/>Aide로 돌아가기</Link><div><span className="doc-badge">PRODUCT UI</span><span className="version">aide-product-ui.md · v{AUI_SCHEMA_VERSION} · {AUI_TOKEN_ENTRIES.length} tokens</span></div></nav>
    <header className="showcase-hero"><div><span className="hero-kicker">AIDE SERVICE DESIGN SYSTEM</span><h1>Aide Product UI</h1><p>Landing, Studio, Playground와 모든 제품 크롬을 위한 단일 시각·상호작용 계약입니다. 이 화면은 서비스의 실제 <code>--aui-*</code> 토큰을 직접 사용합니다.</p></div><div className="principle-list">{['Calm workspace','Blue with purpose','Compact precision','One visual language','Visible system status'].map((item,i)=><div key={item}><b>0{i+1}</b>{item}</div>)}</div></header>
    <nav className="jump-nav">{[['foundations','Foundations'],['actions','Actions'],['inputs','Inputs'],['selection','Selection'],['data','Data display'],['feedback','Feedback'],['overlays','Overlays'],['layouts','Layouts'],['accessibility','Accessibility']].map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav>

    <Section id="foundations" eyebrow="Foundations" title="Color tokens" description="Aide 제품 UI의 시맨틱 색상입니다. 화면 컴포넌트는 직접 색상값을 만들지 않고 이 토큰을 사용합니다."><div className="color-grid">{colors.map(([name,value])=><div className="swatch" key={name}><div className="swatch-color" style={{background:value}}/><div className="swatch-label"><b>{name}</b><code>--aui-{name}</code></div></div>)}</div></Section>
    <Section id="typography" eyebrow="Foundations" title="Typography" description="Pretendard 기반의 제품 UI 타입 스케일입니다. Landing을 제외한 작업 화면은 compact scale을 우선합니다."><div className="type-board">{typeScale.map((t)=><div className="type-row" key={t.name}><span>{t.name}</span><div style={{fontSize:t.size,lineHeight:t.leading,fontWeight:Number(t.weight)}}>Aide로 더 빠르게 설계하세요</div><code>{t.size}/{t.leading} · {t.weight}{t.role?` · ${t.role}`:''}</code></div>)}</div></Section>
    <Section id="tokens" eyebrow="Foundations" title="Spacing, radius, elevation, motion" description="4px 기반 간격과 목적 중심의 radius, elevation, motion 체계입니다."><div className="foundation-grid"><div className="demo-card"><h3>Spacing</h3>{spacing.map(([name,value])=><div className="token-row" key={name}><i className="space-bar" style={{width:value}}/>space-{name} · {value}px</div>)}</div><div className="demo-card"><h3>Radius</h3>{radii.map(([name,value])=><div className="token-row" key={name}><i className="radius-box" style={{borderRadius:value}}/>{name}</div>)}</div><div className="demo-card"><h3>Elevation</h3><div className="shadow-box card">Card</div><div className="shadow-box elevated">Popover / Dialog</div></div><div className="demo-card"><h3>Motion</h3>{motion.map((m)=><div className="token-row" key={m.key}><b>{m.key}</b>{m.value}{m.description?` · ${m.description}`:''}</div>)}</div></div></Section>

    <Section id="actions" eyebrow="Components" title="Actions" description="행동의 우선순위, 위험도, 크기와 상태를 일관되게 표현합니다."><div className="component-grid"><div className="demo-card component-wide"><div className="component-title"><h3>Button variants</h3><span>32 / 40 / 48px</span></div><div className="row"><DemoButton>생성하기</DemoButton><DemoButton variant="secondary">미리보기</DemoButton><DemoButton variant="outline">내보내기</DemoButton><DemoButton variant="ghost">취소</DemoButton><DemoButton variant="destructive">삭제</DemoButton><DemoButton disabled>비활성</DemoButton></div><div className="row" style={{marginTop:12}}><DemoButton variant="primary"><Sparkles size={16}/>AI로 만들기</DemoButton><button className="icon-button" aria-label="알림"><Bell size={17}/></button><button className="icon-button compact" aria-label="더보기"><MoreHorizontal size={16}/></button><DemoButton variant="secondary"><Download size={16}/>다운로드</DemoButton></div></div></div></Section>
    <Section id="inputs" eyebrow="Components" title="Inputs and forms" description="기본, focus, 성공, 오류, 비활성 상태와 선택형 입력을 함께 정의합니다."><div className="component-grid"><div className="demo-card"><div className="component-title"><h3>Text fields</h3><span>default / validation</span></div><div className="form-grid"><Field label="프로젝트 이름" placeholder="이름을 입력하세요"/><Field label="저장 위치" placeholder="Aide Workspace" state="success"/><Field label="공유 이메일" placeholder="name@company.com" state="error"/><Field label="비활성 필드" placeholder="수정할 수 없음" state="disabled"/></div></div><div className="demo-card"><div className="component-title"><h3>Search and select</h3><span>40px control</span></div><div className="stack"><div className="ds-field"><div><Search size={16}/><input placeholder="컴포넌트 검색"/></div></div><div className="ds-field"><div><input value="Gemini 3.1 Pro" readOnly/><ChevronDown size={16}/></div></div><label className="ds-field"><span>설명</span><div style={{height:80,alignItems:'flex-start',paddingTop:10}}><input placeholder="설명을 입력하세요"/></div></label></div></div><div className="demo-card component-wide"><div className="component-title"><h3>Selection controls</h3><span>label + control</span></div><div className="row"><span className="choice"><i className="check-box active"><Check size={13}/></i>자동 저장</span><span className="choice"><i className="check-box"/>댓글 알림</span><span className="choice"><i className="radio-dot active"/>공개</span><span className="choice"><i className="radio-dot"/>비공개</span><span className="choice"><i className="switch active"/>프로토타입 모드</span><span className="choice"><i className="switch"/>개발자 모드</span></div></div></div></Section>
    <Section id="selection" eyebrow="Components" title="Selection and navigation" description="Tabs는 목적지, segmented control은 로컬 모드, chips는 필터에 사용합니다."><div className="component-grid"><div className="demo-card"><h3>Tabs</h3><div className="tabs"><button className="active">Design</button><button>Prototype</button><button>Inspect</button></div><h3 style={{marginTop:24}}>Segmented</h3><div className="segmented"><button className="active">Desktop</button><button>Tablet</button><button>Mobile</button></div></div><div className="demo-card"><h3>Chips and status</h3><div className="row"><span className="chip active">전체</span><span className="chip">레이아웃</span><span className="chip">입력</span><span className="chip"><Plus size={13}/>필터</span></div><div className="row" style={{marginTop:16}}><span className="badge success"><Check size={12}/>저장됨</span><span className="badge warning"><Clock3 size={12}/>생성 중</span><span className="badge">Draft</span></div></div></div></Section>
    <Section id="data" eyebrow="Components" title="Cards, lists and data display" description="정보를 그룹화하되 모든 섹션을 카드로 만들지 않습니다. 반복 데이터는 행과 구분선을 우선합니다."><div className="component-grid"><div className="demo-card"><h3>Metric cards</h3><div className="metric-grid"><div className="metric"><span>생성 시안</span><strong>24</strong></div><div className="metric"><span>완료율</span><strong>82%</strong></div><div className="metric"><span>이번 주</span><strong>+18%</strong></div></div><div className="progress"><i/></div></div><div className="demo-card"><h3>List cells</h3>{[['프로덕트 랜딩','2분 전에 수정됨'],['Studio workspace','자동 저장됨'],['Playground','3개 컴포넌트']].map(([a,b],i)=><div className="list-cell" key={a}><div className="avatar">{i===0?<Sparkles size={16}/>:i===1?<User size={16}/>:<Menu size={16}/>}</div><div className="list-copy"><b>{a}</b><span>{b}</span></div><ChevronRight size={16}/></div>)}</div></div></Section>
    <Section id="feedback" eyebrow="Components" title="Feedback and system status" description="저장, 생성, 오류, 비어 있음과 로딩 상태를 색만이 아니라 아이콘과 문장으로 전달합니다."><div className="component-grid"><div className="demo-card"><h3>Alert and banner</h3><div className="feedback-grid"><div className="feedback info"><Info size={17}/>새로운 Studio 기능을 사용할 수 있어요.</div><div className="feedback success"><Check size={17}/>변경사항을 저장했어요.</div><div className="feedback warning"><AlertCircle size={17}/>연결 상태를 확인하고 있어요.</div><div className="feedback error"><AlertCircle size={17}/>생성에 실패했어요. 다시 시도해 주세요.</div></div></div><div className="demo-card"><h3>Toast and loading</h3><div className="toast"><Check size={16}/><span>링크를 복사했어요.</span><X size={15}/></div><div className="stack" style={{marginTop:18}}><div className="row"><LoaderCircle size={17}/><span style={{fontSize:13}}>컴포넌트를 생성하고 있어요.</span></div><div className="skeleton wide"/><div className="skeleton mid"/></div></div><div className="demo-card component-wide"><div className="empty"><div className="empty-icon"><Upload size={20}/></div><h4>아직 업로드한 파일이 없어요</h4><p>design.md를 추가하면 프로젝트 디자인 시스템을 적용할 수 있어요.</p><DemoButton variant="outline"><Upload size={15}/>파일 추가</DemoButton></div></div></div></Section>
    <Section id="overlays" eyebrow="Components" title="Overlays" description="Dialog, popover와 메뉴는 명확한 제목, 닫기, focus와 행동 계층을 제공합니다."><div className="component-grid"><div className="overlay-stage"><div className="dialog"><div className="dialog-head"><h3>프로젝트를 삭제할까요?</h3><button className="icon-button compact" aria-label="닫기"><X size={16}/></button></div><p>삭제한 프로젝트와 생성 결과는 복구할 수 없습니다.</p><div className="dialog-actions"><DemoButton variant="ghost">취소</DemoButton><DemoButton variant="destructive">프로젝트 삭제</DemoButton></div></div></div><div className="demo-card"><h3>Popover menu</h3><div className="popover"><div><Settings size={15}/>프로젝트 설정</div><div><Download size={15}/>파일로 내보내기</div><div><User size={15}/>멤버 관리</div><div style={{color:'var(--aui-negative)'}}><X size={15}/>프로젝트 나가기</div></div></div></div></Section>
    <Section id="layouts" eyebrow="Patterns" title="Product layout system" description="Landing, Studio, Playground는 같은 제품 언어를 공유하지만 작업 목적에 맞는 shell을 사용합니다."><div className="layout-grid">{[['Landing','Header + Hero + Primary input'],['Studio','AppHeader + Workspace + SidePanel'],['Playground','Toolbar + Library + Canvas + Inspector']].map(([name,desc],index)=><div key={name}><div className="layout-preview"><header/><div className="body">{index>0&&<aside/>}<article><i/><i/><i/><i/></article>{index===2&&<aside/>}</div></div><div className="layout-name"><b>{name}</b><span>{desc}</span></div></div>)}</div></Section>
    <Section id="accessibility" eyebrow="Quality" title="Interaction and accessibility" description="제품 컴포넌트가 구현 단계에서 반드시 만족해야 하는 최소 기준입니다."><div className="a11y-grid">{['32px dense / 40px general / 44px touch target','모든 interactive element에 keyboard focus','Icon-only action에 accessible name','텍스트와 핵심 아이콘 WCAG AA contrast','상태를 색상만으로 전달하지 않음','prefers-reduced-motion 준수','오류 입력값을 보존하고 복구 행동 제공','정적 스타일은 --aui-* 또는 공통 class 사용','Landing·Studio·Playground 동일 primitives 사용'].map(item=><div className="a11y-item" key={item}>{item}</div>)}</div></Section>
  </main>
}
