"use client"

import * as React from "react"
import { ChevronRight, Menu } from "@/components/ui/material-icon"
import { cn } from "@/lib/utils"

type NavigationItem={id:string;label:React.ReactNode;icon?:React.ReactNode;href?:string}
function Navigation({items,activeId,onNavigate,variant="side",label="주요 탐색",className}:{items:NavigationItem[];activeId?:string;onNavigate?:(id:string)=>void;variant?:"top"|"side"|"bottom";label?:string;className?:string}){
  return <nav data-slot="navigation" data-variant={variant} aria-label={label} className={cn(variant==="side"?"grid w-full gap-[var(--aui-space-1)]":variant==="bottom"?"grid w-full grid-flow-col auto-cols-fr border-t border-[var(--aui-border-subtle)] bg-[var(--aui-surface)]":"flex w-full gap-[var(--aui-space-1)] overflow-x-auto border-b border-[var(--aui-border-subtle)]",className)}>{items.map(item=>{const active=item.id===activeId;const content=<>{item.icon}<span className="truncate">{item.label}</span></>;const styles=cn("relative flex min-h-[var(--aui-component-navigation-item-height)] min-w-0 items-center justify-center gap-[var(--aui-component-control-gap)] rounded-[var(--aui-radius-control)] px-[var(--aui-component-control-inline-padding)] text-sm font-medium text-[var(--aui-text-muted)] outline-none transition-[background-color,color,box-shadow] hover:bg-[var(--aui-fill)] focus-visible:shadow-[var(--aui-shadow-focus)] md:min-h-[var(--aui-component-navigation-compact-item-height)]",variant==="side"&&"justify-start",active&&"bg-[var(--aui-primary-soft)] font-semibold text-[var(--aui-primary-heavy)] before:absolute before:bg-[var(--aui-primary)]",active&&variant==="side"&&"before:inset-y-[var(--aui-space-2)] before:left-0 before:w-0.5 before:rounded-full",active&&variant!=="side"&&"before:inset-x-[var(--aui-space-3)] before:bottom-0 before:h-0.5 before:rounded-full");return item.href?<a key={item.id} href={item.href} aria-current={active?"page":undefined} className={styles}>{content}</a>:<button key={item.id} type="button" aria-current={active?"page":undefined} className={styles} onClick={()=>onNavigate?.(item.id)}>{content}</button>})}</nav>
}
function Breadcrumb({items,label="현재 위치",className}:{items:Array<{label:React.ReactNode;href?:string}>;label?:string;className?:string}){return <nav data-slot="breadcrumb" aria-label={label} className={className}><ol className="m-0 flex list-none flex-wrap items-center gap-[var(--aui-component-breadcrumb-gap)] p-0 text-sm">{items.map((item,index)=><li key={index} className="flex items-center gap-[var(--aui-component-breadcrumb-gap)]">{index>0&&<ChevronRight aria-hidden size="var(--aui-icon-sm)" className="text-[var(--aui-text-assistive)]"/>}{item.href?<a href={item.href} className="inline-flex min-h-[var(--aui-component-breadcrumb-item-height)] items-center rounded-[var(--aui-radius-sm)] px-[var(--aui-component-breadcrumb-item-padding-inline)] text-[var(--aui-text-muted)] outline-none hover:text-[var(--aui-primary)] focus-visible:shadow-[var(--aui-shadow-focus)]">{item.label}</a>:<span aria-current="page" className="inline-flex min-h-[var(--aui-component-breadcrumb-item-height)] items-center px-[var(--aui-component-breadcrumb-item-padding-inline)] font-semibold text-[var(--aui-text)]">{item.label}</span>}</li>)}</ol></nav>}
function NavigationMenuButton(props:React.ComponentProps<"button">){return <button type="button" aria-label="탐색 메뉴 열기" className="grid size-[var(--aui-component-navigation-item-height)] place-items-center rounded-[var(--aui-radius-control)] text-[var(--aui-text)] outline-none hover:bg-[var(--aui-fill)] focus-visible:shadow-[var(--aui-shadow-focus)] md:size-[var(--aui-component-navigation-compact-item-height)]" {...props}><Menu size="var(--aui-icon-md)"/></button>}
export {Navigation,Breadcrumb,NavigationMenuButton,type NavigationItem}
