import * as React from "react"
import { Check } from "@/components/ui/material-icon"
import { cn } from "@/lib/utils"

type Step = { id: string; label: React.ReactNode; description?: React.ReactNode }
function Stepper({ steps, current, orientation = "horizontal", className }: { steps: Step[]; current: number; orientation?: "horizontal" | "vertical"; className?: string }) {
  return <ol data-slot="stepper" aria-label="진행 단계" className={cn("m-0 list-none p-0",orientation==="horizontal"?"flex":"grid",className)}>{steps.map((step,index)=>{const complete=index<current,active=index===current;return <li key={step.id} aria-current={active?"step":undefined} className={cn("relative flex min-w-0",orientation==="horizontal"?"flex-1 flex-col items-center text-center":"gap-[var(--aui-component-stepper-item-gap)] pb-[var(--aui-component-stepper-item-padding-block)] last:pb-0")}><div className={cn("relative z-10 grid size-[var(--aui-component-stepper-indicator-size)] shrink-0 place-items-center rounded-full border text-xs font-bold",complete||active?"border-[var(--aui-primary)] bg-[var(--aui-primary)] text-[var(--aui-on-primary)]":"border-[var(--aui-border)] bg-[var(--aui-surface)] text-[var(--aui-text-muted)]")}>{complete?<Check size="var(--aui-icon-sm)"/>:index+1}</div>{index<steps.length-1&&<span aria-hidden className={cn("absolute bg-[var(--aui-border)]",orientation==="horizontal"?"left-1/2 top-[calc(var(--aui-component-stepper-indicator-size)/2)] h-px w-full":"left-[calc(var(--aui-component-stepper-indicator-size)/2)] top-[var(--aui-component-stepper-indicator-size)] h-[calc(100%-var(--aui-component-stepper-indicator-size))] w-px",complete&&"bg-[var(--aui-primary)]")}/>}<div className={cn("min-w-0",orientation==="horizontal"?"mt-[var(--aui-space-2)] px-[var(--aui-component-stepper-label-padding-inline)]":"pt-[var(--aui-space-1)]")}><div className={cn("text-sm font-semibold",active?"text-[var(--aui-primary)]":"text-[var(--aui-text)]")}>{step.label}</div>{step.description&&<div className="mt-0.5 text-xs text-[var(--aui-text-muted)]">{step.description}</div>}</div></li>})}</ol>
}
export { Stepper, type Step }
